/*
 * Created by SharpDevelop.
 * User: sergi
 * Date: 15/06/2016
 * Time: 10:30
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
namespace BW_tool
{
	partial class Entralink_DreamWorld
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		private System.Windows.Forms.ComboBox speciesbox;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.GroupBox Move;
		private System.Windows.Forms.ComboBox movebox;
		private System.Windows.Forms.RadioButton atkC;
		private System.Windows.Forms.RadioButton atkB;
		private System.Windows.Forms.RadioButton atkA;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.RadioButton gnd_none;
		private System.Windows.Forms.RadioButton gnd_male;
		private System.Windows.Forms.RadioButton gnd_female;
		private System.Windows.Forms.Label area_label;
		private System.Windows.Forms.Button ok_but;
		private System.Windows.Forms.Button cancel_but;
		private System.Windows.Forms.Label exclusive_label;
		private System.Windows.Forms.ComboBox moveboxC;
		private System.Windows.Forms.ComboBox moveboxA;
		private System.Windows.Forms.ComboBox pgl_region_box;
		private System.Windows.Forms.Label move_lab;
		private System.Windows.Forms.Label region_lab;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.speciesbox = new System.Windows.Forms.ComboBox();
			this.label1 = new System.Windows.Forms.Label();
			this.Move = new System.Windows.Forms.GroupBox();
			this.move_lab = new System.Windows.Forms.Label();
			this.region_lab = new System.Windows.Forms.Label();
			this.pgl_region_box = new System.Windows.Forms.ComboBox();
			this.movebox = new System.Windows.Forms.ComboBox();
			this.moveboxC = new System.Windows.Forms.ComboBox();
			this.moveboxA = new System.Windows.Forms.ComboBox();
			this.atkC = new System.Windows.Forms.RadioButton();
			this.atkB = new System.Windows.Forms.RadioButton();
			this.atkA = new System.Windows.Forms.RadioButton();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.gnd_none = new System.Windows.Forms.RadioButton();
			this.gnd_male = new System.Windows.Forms.RadioButton();
			this.gnd_female = new System.Windows.Forms.RadioButton();
			this.area_label = new System.Windows.Forms.Label();
			this.ok_but = new System.Windows.Forms.Button();
			this.cancel_but = new System.Windows.Forms.Button();
			this.exclusive_label = new System.Windows.Forms.Label();
			this.Move.SuspendLayout();
			this.groupBox1.SuspendLayout();
			this.SuspendLayout();
			// 
			// speciesbox
			// 
			this.speciesbox.FormattingEnabled = true;
			this.speciesbox.Location = new System.Drawing.Point(5, 94);
			this.speciesbox.Name = "speciesbox";
			this.speciesbox.Size = new System.Drawing.Size(196, 21);
			this.speciesbox.TabIndex = 0;
			this.speciesbox.SelectedIndexChanged += new System.EventHandler(this.SpeciesboxSelectedIndexChanged);
			// 
			// label1
			// 
			this.label1.Location = new System.Drawing.Point(11, 70);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(54, 21);
			this.label1.TabIndex = 1;
			this.label1.Text = "Species";
			this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// Move
			// 
			this.Move.Controls.Add(this.move_lab);
			this.Move.Controls.Add(this.region_lab);
			this.Move.Controls.Add(this.pgl_region_box);
			this.Move.Controls.Add(this.movebox);
			this.Move.Controls.Add(this.moveboxC);
			this.Move.Controls.Add(this.moveboxA);
			this.Move.Controls.Add(this.atkC);
			this.Move.Controls.Add(this.atkB);
			this.Move.Controls.Add(this.atkA);
			this.Move.Location = new System.Drawing.Point(5, 121);
			this.Move.Name = "Move";
			this.Move.Size = new System.Drawing.Size(196, 96);
			this.Move.TabIndex = 2;
			this.Move.TabStop = false;
			this.Move.Text = "Move";
			// 
			// move_lab
			// 
			this.move_lab.Location = new System.Drawing.Point(7, 45);
			this.move_lab.Name = "move_lab";
			this.move_lab.Size = new System.Drawing.Size(42, 23);
			this.move_lab.TabIndex = 8;
			this.move_lab.Text = "Move";
			// 
			// region_lab
			// 
			this.region_lab.Location = new System.Drawing.Point(7, 25);
			this.region_lab.Name = "region_lab";
			this.region_lab.Size = new System.Drawing.Size(42, 23);
			this.region_lab.TabIndex = 7;
			this.region_lab.Text = "Region";
			// 
			// pgl_region_box
			// 
			this.pgl_region_box.DropDownStyle = System.Windows.Forms.ComboBoxStyle.Simple;
			this.pgl_region_box.FormattingEnabled = true;
			this.pgl_region_box.Items.AddRange(new object[] {
			"ALL",
			"ALL",
			"ALL",
			"ALL",
			"ALL",
			"ALL",
			"ALL",
			"JAP and KOR",
			"JAP and KOR",
			"JAP and KOR",
			"JAP and KOR",
			"JAP and KOR",
			"JAP and KOR",
			"JAP and KOR",
			"JAP, USA, EUR",
			"JAP",
			"JAP",
			"JAP",
			"ALL",
			"ALL",
			"ALL",
			"KOR",
			"ALL",
			"EUR",
			"JAP",
			"JAP and KOR",
			"ALL",
			"ALL",
			"JAP, USA and EUR (Intended for Germany, Italy, UK)",
			"KOR",
			"JAP",
			"JAP",
			"JAP",
			"USA and EUR (Intended for USA only)",
			"USA and EUR (Intended for USA only)",
			"USA and EUR (Intended for USA only)",
			"JAP",
			"USA and EUR",
			"USA and EUR",
			"JAP and KOR",
			"USA and EUR",
			"USA and EUR",
			"USA and EUR"});
			this.pgl_region_box.Location = new System.Drawing.Point(52, 19);
			this.pgl_region_box.Name = "pgl_region_box";
			this.pgl_region_box.Size = new System.Drawing.Size(119, 21);
			this.pgl_region_box.TabIndex = 6;
			// 
			// movebox
			// 
			this.movebox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.Simple;
			this.movebox.FormattingEnabled = true;
			this.movebox.Items.AddRange(new object[] {
			"----------------------",
			"Pound",
			"Karate Chop",
			"Double Slap",
			"Comet Punch",
			"Mega Punch",
			"Pay Day",
			"Fire Punch",
			"Ice Punch",
			"Thunder Punch",
			"Scratch",
			"Vice Grip",
			"Guillotine",
			"Razor Wind",
			"Swords Dance",
			"Cut",
			"Gust",
			"Wing Attack",
			"Whirlwind",
			"Fly",
			"Bind",
			"Slam",
			"Vine Whip",
			"Stomp",
			"Double Kick",
			"Mega Kick",
			"Jump Kick",
			"Rolling Kick",
			"Sand Attack",
			"Headbutt",
			"Horn Attack",
			"Fury Attack",
			"Horn Drill",
			"Tackle",
			"Body Slam",
			"Wrap",
			"Take Down",
			"Thrash",
			"Double-Edge",
			"Tail Whip",
			"Poison Sting",
			"Twineedle",
			"Pin Missile",
			"Leer",
			"Bite",
			"Growl",
			"Roar",
			"Sing",
			"Supersonic",
			"Sonic Boom",
			"Disable",
			"Acid",
			"Ember",
			"Flamethrower",
			"Mist",
			"Water Gun",
			"Hydro Pump",
			"Surf",
			"Ice Beam",
			"Blizzard",
			"Psybeam",
			"Bubble Beam",
			"Aurora Beam",
			"Hyper Beam",
			"Peck",
			"Drill Peck",
			"Submission",
			"Low Kick",
			"Counter",
			"Seismic Toss",
			"Strength",
			"Absorb",
			"Mega Drain",
			"Leech Seed",
			"Growth",
			"Razor Leaf",
			"Solar Beam",
			"Poison Powder",
			"Stun Spore",
			"Sleep Powder",
			"Petal Dance",
			"String Shot",
			"Dragon Rage",
			"Fire Spin",
			"Thunder Shock",
			"Thunderbolt",
			"Thunder Wave",
			"Thunder",
			"Rock Throw",
			"Earthquake",
			"Fissure",
			"Dig",
			"Toxic",
			"Confusion",
			"Psychic",
			"Hypnosis",
			"Meditate",
			"Agility",
			"Quick Attack",
			"Rage",
			"Teleport",
			"Night Shade",
			"Mimic",
			"Screech",
			"Double Team",
			"Recover",
			"Harden",
			"Minimize",
			"Smokescreen",
			"Confuse Ray",
			"Withdraw",
			"Defense Curl",
			"Barrier",
			"Light Screen",
			"Haze",
			"Reflect",
			"Focus Energy",
			"Bide",
			"Metronome",
			"Mirror Move",
			"Self-Destruct",
			"Egg Bomb",
			"Lick",
			"Smog",
			"Sludge",
			"Bone Club",
			"Fire Blast",
			"Waterfall",
			"Clamp",
			"Swift",
			"Skull Bash",
			"Spike Cannon",
			"Constrict",
			"Amnesia",
			"Kinesis",
			"Soft-Boiled",
			"High Jump Kick",
			"Glare",
			"Dream Eater",
			"Poison Gas",
			"Barrage",
			"Leech Life",
			"Lovely Kiss",
			"Sky Attack",
			"Transform",
			"Bubble",
			"Dizzy Punch",
			"Spore",
			"Flash",
			"Psywave",
			"Splash",
			"Acid Armor",
			"Crabhammer",
			"Explosion",
			"Fury Swipes",
			"Bonemerang",
			"Rest",
			"Rock Slide",
			"Hyper Fang",
			"Sharpen",
			"Conversion",
			"Tri Attack",
			"Super Fang",
			"Slash",
			"Substitute",
			"Struggle",
			"Sketch",
			"Triple Kick",
			"Thief",
			"Spider Web",
			"Mind Reader",
			"Nightmare",
			"Flame Wheel",
			"Snore",
			"Curse",
			"Flail",
			"Conversion 2",
			"Aeroblast",
			"Cotton Spore",
			"Reversal",
			"Spite",
			"Powder Snow",
			"Protect",
			"Mach Punch",
			"Scary Face",
			"Feint Attack",
			"Sweet Kiss",
			"Belly Drum",
			"Sludge Bomb",
			"Mud-Slap",
			"Octazooka",
			"Spikes",
			"Zap Cannon",
			"Foresight",
			"Destiny Bond",
			"Perish Song",
			"Icy Wind",
			"Detect",
			"Bone Rush",
			"Lock-On",
			"Outrage",
			"Sandstorm",
			"Giga Drain",
			"Endure",
			"Charm",
			"Rollout",
			"False Swipe",
			"Swagger",
			"Milk Drink",
			"Spark",
			"Fury Cutter",
			"Steel Wing",
			"Mean Look",
			"Attract",
			"Sleep Talk",
			"Heal Bell",
			"Return",
			"Present",
			"Frustration",
			"Safeguard",
			"Pain Split",
			"Sacred Fire",
			"Magnitude",
			"Dynamic Punch",
			"Megahorn",
			"Dragon Breath",
			"Baton Pass",
			"Encore",
			"Pursuit",
			"Rapid Spin",
			"Sweet Scent",
			"Iron Tail",
			"Metal Claw",
			"Vital Throw",
			"Morning Sun",
			"Synthesis",
			"Moonlight",
			"Hidden Power",
			"Cross Chop",
			"Twister",
			"Rain Dance",
			"Sunny Day",
			"Crunch",
			"Mirror Coat",
			"Psych Up",
			"Extreme Speed",
			"Ancient Power",
			"Shadow Ball",
			"Future Sight",
			"Rock Smash",
			"Whirlpool",
			"Beat Up",
			"Fake Out",
			"Uproar",
			"Stockpile",
			"Spit Up",
			"Swallow",
			"Heat Wave",
			"Hail",
			"Torment",
			"Flatter",
			"Will-O-Wisp",
			"Memento",
			"Facade",
			"Focus Punch",
			"Smelling Salts",
			"Follow Me",
			"Nature Power",
			"Charge",
			"Taunt",
			"Helping Hand",
			"Trick",
			"Role Play",
			"Wish",
			"Assist",
			"Ingrain",
			"Superpower",
			"Magic Coat",
			"Recycle",
			"Revenge",
			"Brick Break",
			"Yawn",
			"Knock Off",
			"Endeavor",
			"Eruption",
			"Skill Swap",
			"Imprison",
			"Refresh",
			"Grudge",
			"Snatch",
			"Secret Power",
			"Dive",
			"Arm Thrust",
			"Camouflage",
			"Tail Glow",
			"Luster Purge",
			"Mist Ball",
			"Feather Dance",
			"Teeter Dance",
			"Blaze Kick",
			"Mud Sport",
			"Ice Ball",
			"Needle Arm",
			"Slack Off",
			"Hyper Voice",
			"Poison Fang",
			"Crush Claw",
			"Blast Burn",
			"Hydro Cannon",
			"Meteor Mash",
			"Astonish",
			"Weather Ball",
			"Aromatherapy",
			"Fake Tears",
			"Air Cutter",
			"Overheat",
			"Odor Sleuth",
			"Rock Tomb",
			"Silver Wind",
			"Metal Sound",
			"Grass Whistle",
			"Tickle",
			"Cosmic Power",
			"Water Spout",
			"Signal Beam",
			"Shadow Punch",
			"Extrasensory",
			"Sky Uppercut",
			"Sand Tomb",
			"Sheer Cold",
			"Muddy Water",
			"Bullet Seed",
			"Aerial Ace",
			"Icicle Spear",
			"Iron Defense",
			"Block",
			"Howl",
			"Dragon Claw",
			"Frenzy Plant",
			"Bulk Up",
			"Bounce",
			"Mud Shot",
			"Poison Tail",
			"Covet",
			"Volt Tackle",
			"Magical Leaf",
			"Water Sport",
			"Calm Mind",
			"Leaf Blade",
			"Dragon Dance",
			"Rock Blast",
			"Shock Wave",
			"Water Pulse",
			"Doom Desire",
			"Psycho Boost",
			"Roost",
			"Gravity",
			"Miracle Eye",
			"Wake-Up Slap",
			"Hammer Arm",
			"Gyro Ball",
			"Healing Wish",
			"Brine",
			"Natural Gift",
			"Feint",
			"Pluck",
			"Tailwind",
			"Acupressure",
			"Metal Burst",
			"U-turn",
			"Close Combat",
			"Payback",
			"Assurance",
			"Embargo",
			"Fling",
			"Psycho Shift",
			"Trump Card",
			"Heal Block",
			"Wring Out",
			"Power Trick",
			"Gastro Acid",
			"Lucky Chant",
			"Me First",
			"Copycat",
			"Power Swap",
			"Guard Swap",
			"Punishment",
			"Last Resort",
			"Worry Seed",
			"Sucker Punch",
			"Toxic Spikes",
			"Heart Swap",
			"Aqua Ring",
			"Magnet Rise",
			"Flare Blitz",
			"Force Palm",
			"Aura Sphere",
			"Rock Polish",
			"Poison Jab",
			"Dark Pulse",
			"Night Slash",
			"Aqua Tail",
			"Seed Bomb",
			"Air Slash",
			"X-Scissor",
			"Bug Buzz",
			"Dragon Pulse",
			"Dragon Rush",
			"Power Gem",
			"Drain Punch",
			"Vacuum Wave",
			"Focus Blast",
			"Energy Ball",
			"Brave Bird",
			"Earth Power",
			"Switcheroo",
			"Giga Impact",
			"Nasty Plot",
			"Bullet Punch",
			"Avalanche",
			"Ice Shard",
			"Shadow Claw",
			"Thunder Fang",
			"Ice Fang",
			"Fire Fang",
			"Shadow Sneak",
			"Mud Bomb",
			"Psycho Cut",
			"Zen Headbutt",
			"Mirror Shot",
			"Flash Cannon",
			"Rock Climb",
			"Defog",
			"Trick Room",
			"Draco Meteor",
			"Discharge",
			"Lava Plume",
			"Leaf Storm",
			"Power Whip",
			"Rock Wrecker",
			"Cross Poison",
			"Gunk Shot",
			"Iron Head",
			"Magnet Bomb",
			"Stone Edge",
			"Captivate",
			"Stealth Rock",
			"Grass Knot",
			"Chatter",
			"Judgment",
			"Bug Bite",
			"Charge Beam",
			"Wood Hammer",
			"Aqua Jet",
			"Attack Order",
			"Defend Order",
			"Heal Order",
			"Head Smash",
			"Double Hit",
			"Roar of Time",
			"Spacial Rend",
			"Lunar Dance",
			"Crush Grip",
			"Magma Storm",
			"Dark Void",
			"Seed Flare",
			"Ominous Wind",
			"Shadow Force",
			"Hone Claws",
			"Wide Guard",
			"Guard Split",
			"Power Split",
			"Wonder Room",
			"Psyshock",
			"Venoshock",
			"Autotomize",
			"Rage Powder",
			"Telekinesis",
			"Magic Room",
			"Smack Down",
			"Storm Throw",
			"Flame Burst",
			"Sludge Wave",
			"Quiver Dance",
			"Heavy Slam",
			"Synchronoise",
			"Electro Ball",
			"Soak",
			"Flame Charge",
			"Coil",
			"Low Sweep",
			"Acid Spray",
			"Foul Play",
			"Simple Beam",
			"Entrainment",
			"After You",
			"Round",
			"Echoed Voice",
			"Chip Away",
			"Clear Smog",
			"Stored Power",
			"Quick Guard",
			"Ally Switch",
			"Scald",
			"Shell Smash",
			"Heal Pulse",
			"Hex",
			"Sky Drop",
			"Shift Gear",
			"Circle Throw",
			"Incinerate",
			"Quash",
			"Acrobatics",
			"Reflect Type",
			"Retaliate",
			"Final Gambit",
			"Bestow",
			"Inferno",
			"Water Pledge",
			"Fire Pledge",
			"Grass Pledge",
			"Volt Switch",
			"Struggle Bug",
			"Bulldoze",
			"Frost Breath",
			"Dragon Tail",
			"Work Up",
			"Electroweb",
			"Wild Charge",
			"Drill Run",
			"Dual Chop",
			"Heart Stamp",
			"Horn Leech",
			"Sacred Sword",
			"Razor Shell",
			"Heat Crash",
			"Leaf Tornado",
			"Steamroller",
			"Cotton Guard",
			"Night Daze",
			"Psystrike",
			"Tail Slap",
			"Hurricane",
			"Head Charge",
			"Gear Grind",
			"Searing Shot",
			"Techno Blast",
			"Relic Song",
			"Secret Sword",
			"Glaciate",
			"Bolt Strike",
			"Blue Flare",
			"Fiery Dance",
			"Freeze Shock",
			"Ice Burn",
			"Snarl",
			"Icicle Crash",
			"V-create",
			"Fusion Flare",
			"Fusion Bolt"});
			this.movebox.Location = new System.Drawing.Point(52, 42);
			this.movebox.Name = "movebox";
			this.movebox.Size = new System.Drawing.Size(119, 21);
			this.movebox.TabIndex = 3;
			// 
			// moveboxC
			// 
			this.moveboxC.DropDownStyle = System.Windows.Forms.ComboBoxStyle.Simple;
			this.moveboxC.FormattingEnabled = true;
			this.moveboxC.Items.AddRange(new object[] {
			"----------------------",
			"Pound",
			"Karate Chop",
			"Double Slap",
			"Comet Punch",
			"Mega Punch",
			"Pay Day",
			"Fire Punch",
			"Ice Punch",
			"Thunder Punch",
			"Scratch",
			"Vice Grip",
			"Guillotine",
			"Razor Wind",
			"Swords Dance",
			"Cut",
			"Gust",
			"Wing Attack",
			"Whirlwind",
			"Fly",
			"Bind",
			"Slam",
			"Vine Whip",
			"Stomp",
			"Double Kick",
			"Mega Kick",
			"Jump Kick",
			"Rolling Kick",
			"Sand Attack",
			"Headbutt",
			"Horn Attack",
			"Fury Attack",
			"Horn Drill",
			"Tackle",
			"Body Slam",
			"Wrap",
			"Take Down",
			"Thrash",
			"Double-Edge",
			"Tail Whip",
			"Poison Sting",
			"Twineedle",
			"Pin Missile",
			"Leer",
			"Bite",
			"Growl",
			"Roar",
			"Sing",
			"Supersonic",
			"Sonic Boom",
			"Disable",
			"Acid",
			"Ember",
			"Flamethrower",
			"Mist",
			"Water Gun",
			"Hydro Pump",
			"Surf",
			"Ice Beam",
			"Blizzard",
			"Psybeam",
			"Bubble Beam",
			"Aurora Beam",
			"Hyper Beam",
			"Peck",
			"Drill Peck",
			"Submission",
			"Low Kick",
			"Counter",
			"Seismic Toss",
			"Strength",
			"Absorb",
			"Mega Drain",
			"Leech Seed",
			"Growth",
			"Razor Leaf",
			"Solar Beam",
			"Poison Powder",
			"Stun Spore",
			"Sleep Powder",
			"Petal Dance",
			"String Shot",
			"Dragon Rage",
			"Fire Spin",
			"Thunder Shock",
			"Thunderbolt",
			"Thunder Wave",
			"Thunder",
			"Rock Throw",
			"Earthquake",
			"Fissure",
			"Dig",
			"Toxic",
			"Confusion",
			"Psychic",
			"Hypnosis",
			"Meditate",
			"Agility",
			"Quick Attack",
			"Rage",
			"Teleport",
			"Night Shade",
			"Mimic",
			"Screech",
			"Double Team",
			"Recover",
			"Harden",
			"Minimize",
			"Smokescreen",
			"Confuse Ray",
			"Withdraw",
			"Defense Curl",
			"Barrier",
			"Light Screen",
			"Haze",
			"Reflect",
			"Focus Energy",
			"Bide",
			"Metronome",
			"Mirror Move",
			"Self-Destruct",
			"Egg Bomb",
			"Lick",
			"Smog",
			"Sludge",
			"Bone Club",
			"Fire Blast",
			"Waterfall",
			"Clamp",
			"Swift",
			"Skull Bash",
			"Spike Cannon",
			"Constrict",
			"Amnesia",
			"Kinesis",
			"Soft-Boiled",
			"High Jump Kick",
			"Glare",
			"Dream Eater",
			"Poison Gas",
			"Barrage",
			"Leech Life",
			"Lovely Kiss",
			"Sky Attack",
			"Transform",
			"Bubble",
			"Dizzy Punch",
			"Spore",
			"Flash",
			"Psywave",
			"Splash",
			"Acid Armor",
			"Crabhammer",
			"Explosion",
			"Fury Swipes",
			"Bonemerang",
			"Rest",
			"Rock Slide",
			"Hyper Fang",
			"Sharpen",
			"Conversion",
			"Tri Attack",
			"Super Fang",
			"Slash",
			"Substitute",
			"Struggle",
			"Sketch",
			"Triple Kick",
			"Thief",
			"Spider Web",
			"Mind Reader",
			"Nightmare",
			"Flame Wheel",
			"Snore",
			"Curse",
			"Flail",
			"Conversion 2",
			"Aeroblast",
			"Cotton Spore",
			"Reversal",
			"Spite",
			"Powder Snow",
			"Protect",
			"Mach Punch",
			"Scary Face",
			"Feint Attack",
			"Sweet Kiss",
			"Belly Drum",
			"Sludge Bomb",
			"Mud-Slap",
			"Octazooka",
			"Spikes",
			"Zap Cannon",
			"Foresight",
			"Destiny Bond",
			"Perish Song",
			"Icy Wind",
			"Detect",
			"Bone Rush",
			"Lock-On",
			"Outrage",
			"Sandstorm",
			"Giga Drain",
			"Endure",
			"Charm",
			"Rollout",
			"False Swipe",
			"Swagger",
			"Milk Drink",
			"Spark",
			"Fury Cutter",
			"Steel Wing",
			"Mean Look",
			"Attract",
			"Sleep Talk",
			"Heal Bell",
			"Return",
			"Present",
			"Frustration",
			"Safeguard",
			"Pain Split",
			"Sacred Fire",
			"Magnitude",
			"Dynamic Punch",
			"Megahorn",
			"Dragon Breath",
			"Baton Pass",
			"Encore",
			"Pursuit",
			"Rapid Spin",
			"Sweet Scent",
			"Iron Tail",
			"Metal Claw",
			"Vital Throw",
			"Morning Sun",
			"Synthesis",
			"Moonlight",
			"Hidden Power",
			"Cross Chop",
			"Twister",
			"Rain Dance",
			"Sunny Day",
			"Crunch",
			"Mirror Coat",
			"Psych Up",
			"Extreme Speed",
			"Ancient Power",
			"Shadow Ball",
			"Future Sight",
			"Rock Smash",
			"Whirlpool",
			"Beat Up",
			"Fake Out",
			"Uproar",
			"Stockpile",
			"Spit Up",
			"Swallow",
			"Heat Wave",
			"Hail",
			"Torment",
			"Flatter",
			"Will-O-Wisp",
			"Memento",
			"Facade",
			"Focus Punch",
			"Smelling Salts",
			"Follow Me",
			"Nature Power",
			"Charge",
			"Taunt",
			"Helping Hand",
			"Trick",
			"Role Play",
			"Wish",
			"Assist",
			"Ingrain",
			"Superpower",
			"Magic Coat",
			"Recycle",
			"Revenge",
			"Brick Break",
			"Yawn",
			"Knock Off",
			"Endeavor",
			"Eruption",
			"Skill Swap",
			"Imprison",
			"Refresh",
			"Grudge",
			"Snatch",
			"Secret Power",
			"Dive",
			"Arm Thrust",
			"Camouflage",
			"Tail Glow",
			"Luster Purge",
			"Mist Ball",
			"Feather Dance",
			"Teeter Dance",
			"Blaze Kick",
			"Mud Sport",
			"Ice Ball",
			"Needle Arm",
			"Slack Off",
			"Hyper Voice",
			"Poison Fang",
			"Crush Claw",
			"Blast Burn",
			"Hydro Cannon",
			"Meteor Mash",
			"Astonish",
			"Weather Ball",
			"Aromatherapy",
			"Fake Tears",
			"Air Cutter",
			"Overheat",
			"Odor Sleuth",
			"Rock Tomb",
			"Silver Wind",
			"Metal Sound",
			"Grass Whistle",
			"Tickle",
			"Cosmic Power",
			"Water Spout",
			"Signal Beam",
			"Shadow Punch",
			"Extrasensory",
			"Sky Uppercut",
			"Sand Tomb",
			"Sheer Cold",
			"Muddy Water",
			"Bullet Seed",
			"Aerial Ace",
			"Icicle Spear",
			"Iron Defense",
			"Block",
			"Howl",
			"Dragon Claw",
			"Frenzy Plant",
			"Bulk Up",
			"Bounce",
			"Mud Shot",
			"Poison Tail",
			"Covet",
			"Volt Tackle",
			"Magical Leaf",
			"Water Sport",
			"Calm Mind",
			"Leaf Blade",
			"Dragon Dance",
			"Rock Blast",
			"Shock Wave",
			"Water Pulse",
			"Doom Desire",
			"Psycho Boost",
			"Roost",
			"Gravity",
			"Miracle Eye",
			"Wake-Up Slap",
			"Hammer Arm",
			"Gyro Ball",
			"Healing Wish",
			"Brine",
			"Natural Gift",
			"Feint",
			"Pluck",
			"Tailwind",
			"Acupressure",
			"Metal Burst",
			"U-turn",
			"Close Combat",
			"Payback",
			"Assurance",
			"Embargo",
			"Fling",
			"Psycho Shift",
			"Trump Card",
			"Heal Block",
			"Wring Out",
			"Power Trick",
			"Gastro Acid",
			"Lucky Chant",
			"Me First",
			"Copycat",
			"Power Swap",
			"Guard Swap",
			"Punishment",
			"Last Resort",
			"Worry Seed",
			"Sucker Punch",
			"Toxic Spikes",
			"Heart Swap",
			"Aqua Ring",
			"Magnet Rise",
			"Flare Blitz",
			"Force Palm",
			"Aura Sphere",
			"Rock Polish",
			"Poison Jab",
			"Dark Pulse",
			"Night Slash",
			"Aqua Tail",
			"Seed Bomb",
			"Air Slash",
			"X-Scissor",
			"Bug Buzz",
			"Dragon Pulse",
			"Dragon Rush",
			"Power Gem",
			"Drain Punch",
			"Vacuum Wave",
			"Focus Blast",
			"Energy Ball",
			"Brave Bird",
			"Earth Power",
			"Switcheroo",
			"Giga Impact",
			"Nasty Plot",
			"Bullet Punch",
			"Avalanche",
			"Ice Shard",
			"Shadow Claw",
			"Thunder Fang",
			"Ice Fang",
			"Fire Fang",
			"Shadow Sneak",
			"Mud Bomb",
			"Psycho Cut",
			"Zen Headbutt",
			"Mirror Shot",
			"Flash Cannon",
			"Rock Climb",
			"Defog",
			"Trick Room",
			"Draco Meteor",
			"Discharge",
			"Lava Plume",
			"Leaf Storm",
			"Power Whip",
			"Rock Wrecker",
			"Cross Poison",
			"Gunk Shot",
			"Iron Head",
			"Magnet Bomb",
			"Stone Edge",
			"Captivate",
			"Stealth Rock",
			"Grass Knot",
			"Chatter",
			"Judgment",
			"Bug Bite",
			"Charge Beam",
			"Wood Hammer",
			"Aqua Jet",
			"Attack Order",
			"Defend Order",
			"Heal Order",
			"Head Smash",
			"Double Hit",
			"Roar of Time",
			"Spacial Rend",
			"Lunar Dance",
			"Crush Grip",
			"Magma Storm",
			"Dark Void",
			"Seed Flare",
			"Ominous Wind",
			"Shadow Force",
			"Hone Claws",
			"Wide Guard",
			"Guard Split",
			"Power Split",
			"Wonder Room",
			"Psyshock",
			"Venoshock",
			"Autotomize",
			"Rage Powder",
			"Telekinesis",
			"Magic Room",
			"Smack Down",
			"Storm Throw",
			"Flame Burst",
			"Sludge Wave",
			"Quiver Dance",
			"Heavy Slam",
			"Synchronoise",
			"Electro Ball",
			"Soak",
			"Flame Charge",
			"Coil",
			"Low Sweep",
			"Acid Spray",
			"Foul Play",
			"Simple Beam",
			"Entrainment",
			"After You",
			"Round",
			"Echoed Voice",
			"Chip Away",
			"Clear Smog",
			"Stored Power",
			"Quick Guard",
			"Ally Switch",
			"Scald",
			"Shell Smash",
			"Heal Pulse",
			"Hex",
			"Sky Drop",
			"Shift Gear",
			"Circle Throw",
			"Incinerate",
			"Quash",
			"Acrobatics",
			"Reflect Type",
			"Retaliate",
			"Final Gambit",
			"Bestow",
			"Inferno",
			"Water Pledge",
			"Fire Pledge",
			"Grass Pledge",
			"Volt Switch",
			"Struggle Bug",
			"Bulldoze",
			"Frost Breath",
			"Dragon Tail",
			"Work Up",
			"Electroweb",
			"Wild Charge",
			"Drill Run",
			"Dual Chop",
			"Heart Stamp",
			"Horn Leech",
			"Sacred Sword",
			"Razor Shell",
			"Heat Crash",
			"Leaf Tornado",
			"Steamroller",
			"Cotton Guard",
			"Night Daze",
			"Psystrike",
			"Tail Slap",
			"Hurricane",
			"Head Charge",
			"Gear Grind",
			"Searing Shot",
			"Techno Blast",
			"Relic Song",
			"Secret Sword",
			"Glaciate",
			"Bolt Strike",
			"Blue Flare",
			"Fiery Dance",
			"Freeze Shock",
			"Ice Burn",
			"Snarl",
			"Icicle Crash",
			"V-create",
			"Fusion Flare",
			"Fusion Bolt"});
			this.moveboxC.Location = new System.Drawing.Point(52, 64);
			this.moveboxC.Name = "moveboxC";
			this.moveboxC.Size = new System.Drawing.Size(119, 21);
			this.moveboxC.TabIndex = 5;
			// 
			// moveboxA
			// 
			this.moveboxA.DropDownStyle = System.Windows.Forms.ComboBoxStyle.Simple;
			this.moveboxA.FormattingEnabled = true;
			this.moveboxA.Items.AddRange(new object[] {
			"----------------------",
			"Pound",
			"Karate Chop",
			"Double Slap",
			"Comet Punch",
			"Mega Punch",
			"Pay Day",
			"Fire Punch",
			"Ice Punch",
			"Thunder Punch",
			"Scratch",
			"Vice Grip",
			"Guillotine",
			"Razor Wind",
			"Swords Dance",
			"Cut",
			"Gust",
			"Wing Attack",
			"Whirlwind",
			"Fly",
			"Bind",
			"Slam",
			"Vine Whip",
			"Stomp",
			"Double Kick",
			"Mega Kick",
			"Jump Kick",
			"Rolling Kick",
			"Sand Attack",
			"Headbutt",
			"Horn Attack",
			"Fury Attack",
			"Horn Drill",
			"Tackle",
			"Body Slam",
			"Wrap",
			"Take Down",
			"Thrash",
			"Double-Edge",
			"Tail Whip",
			"Poison Sting",
			"Twineedle",
			"Pin Missile",
			"Leer",
			"Bite",
			"Growl",
			"Roar",
			"Sing",
			"Supersonic",
			"Sonic Boom",
			"Disable",
			"Acid",
			"Ember",
			"Flamethrower",
			"Mist",
			"Water Gun",
			"Hydro Pump",
			"Surf",
			"Ice Beam",
			"Blizzard",
			"Psybeam",
			"Bubble Beam",
			"Aurora Beam",
			"Hyper Beam",
			"Peck",
			"Drill Peck",
			"Submission",
			"Low Kick",
			"Counter",
			"Seismic Toss",
			"Strength",
			"Absorb",
			"Mega Drain",
			"Leech Seed",
			"Growth",
			"Razor Leaf",
			"Solar Beam",
			"Poison Powder",
			"Stun Spore",
			"Sleep Powder",
			"Petal Dance",
			"String Shot",
			"Dragon Rage",
			"Fire Spin",
			"Thunder Shock",
			"Thunderbolt",
			"Thunder Wave",
			"Thunder",
			"Rock Throw",
			"Earthquake",
			"Fissure",
			"Dig",
			"Toxic",
			"Confusion",
			"Psychic",
			"Hypnosis",
			"Meditate",
			"Agility",
			"Quick Attack",
			"Rage",
			"Teleport",
			"Night Shade",
			"Mimic",
			"Screech",
			"Double Team",
			"Recover",
			"Harden",
			"Minimize",
			"Smokescreen",
			"Confuse Ray",
			"Withdraw",
			"Defense Curl",
			"Barrier",
			"Light Screen",
			"Haze",
			"Reflect",
			"Focus Energy",
			"Bide",
			"Metronome",
			"Mirror Move",
			"Self-Destruct",
			"Egg Bomb",
			"Lick",
			"Smog",
			"Sludge",
			"Bone Club",
			"Fire Blast",
			"Waterfall",
			"Clamp",
			"Swift",
			"Skull Bash",
			"Spike Cannon",
			"Constrict",
			"Amnesia",
			"Kinesis",
			"Soft-Boiled",
			"High Jump Kick",
			"Glare",
			"Dream Eater",
			"Poison Gas",
			"Barrage",
			"Leech Life",
			"Lovely Kiss",
			"Sky Attack",
			"Transform",
			"Bubble",
			"Dizzy Punch",
			"Spore",
			"Flash",
			"Psywave",
			"Splash",
			"Acid Armor",
			"Crabhammer",
			"Explosion",
			"Fury Swipes",
			"Bonemerang",
			"Rest",
			"Rock Slide",
			"Hyper Fang",
			"Sharpen",
			"Conversion",
			"Tri Attack",
			"Super Fang",
			"Slash",
			"Substitute",
			"Struggle",
			"Sketch",
			"Triple Kick",
			"Thief",
			"Spider Web",
			"Mind Reader",
			"Nightmare",
			"Flame Wheel",
			"Snore",
			"Curse",
			"Flail",
			"Conversion 2",
			"Aeroblast",
			"Cotton Spore",
			"Reversal",
			"Spite",
			"Powder Snow",
			"Protect",
			"Mach Punch",
			"Scary Face",
			"Feint Attack",
			"Sweet Kiss",
			"Belly Drum",
			"Sludge Bomb",
			"Mud-Slap",
			"Octazooka",
			"Spikes",
			"Zap Cannon",
			"Foresight",
			"Destiny Bond",
			"Perish Song",
			"Icy Wind",
			"Detect",
			"Bone Rush",
			"Lock-On",
			"Outrage",
			"Sandstorm",
			"Giga Drain",
			"Endure",
			"Charm",
			"Rollout",
			"False Swipe",
			"Swagger",
			"Milk Drink",
			"Spark",
			"Fury Cutter",
			"Steel Wing",
			"Mean Look",
			"Attract",
			"Sleep Talk",
			"Heal Bell",
			"Return",
			"Present",
			"Frustration",
			"Safeguard",
			"Pain Split",
			"Sacred Fire",
			"Magnitude",
			"Dynamic Punch",
			"Megahorn",
			"Dragon Breath",
			"Baton Pass",
			"Encore",
			"Pursuit",
			"Rapid Spin",
			"Sweet Scent",
			"Iron Tail",
			"Metal Claw",
			"Vital Throw",
			"Morning Sun",
			"Synthesis",
			"Moonlight",
			"Hidden Power",
			"Cross Chop",
			"Twister",
			"Rain Dance",
			"Sunny Day",
			"Crunch",
			"Mirror Coat",
			"Psych Up",
			"Extreme Speed",
			"Ancient Power",
			"Shadow Ball",
			"Future Sight",
			"Rock Smash",
			"Whirlpool",
			"Beat Up",
			"Fake Out",
			"Uproar",
			"Stockpile",
			"Spit Up",
			"Swallow",
			"Heat Wave",
			"Hail",
			"Torment",
			"Flatter",
			"Will-O-Wisp",
			"Memento",
			"Facade",
			"Focus Punch",
			"Smelling Salts",
			"Follow Me",
			"Nature Power",
			"Charge",
			"Taunt",
			"Helping Hand",
			"Trick",
			"Role Play",
			"Wish",
			"Assist",
			"Ingrain",
			"Superpower",
			"Magic Coat",
			"Recycle",
			"Revenge",
			"Brick Break",
			"Yawn",
			"Knock Off",
			"Endeavor",
			"Eruption",
			"Skill Swap",
			"Imprison",
			"Refresh",
			"Grudge",
			"Snatch",
			"Secret Power",
			"Dive",
			"Arm Thrust",
			"Camouflage",
			"Tail Glow",
			"Luster Purge",
			"Mist Ball",
			"Feather Dance",
			"Teeter Dance",
			"Blaze Kick",
			"Mud Sport",
			"Ice Ball",
			"Needle Arm",
			"Slack Off",
			"Hyper Voice",
			"Poison Fang",
			"Crush Claw",
			"Blast Burn",
			"Hydro Cannon",
			"Meteor Mash",
			"Astonish",
			"Weather Ball",
			"Aromatherapy",
			"Fake Tears",
			"Air Cutter",
			"Overheat",
			"Odor Sleuth",
			"Rock Tomb",
			"Silver Wind",
			"Metal Sound",
			"Grass Whistle",
			"Tickle",
			"Cosmic Power",
			"Water Spout",
			"Signal Beam",
			"Shadow Punch",
			"Extrasensory",
			"Sky Uppercut",
			"Sand Tomb",
			"Sheer Cold",
			"Muddy Water",
			"Bullet Seed",
			"Aerial Ace",
			"Icicle Spear",
			"Iron Defense",
			"Block",
			"Howl",
			"Dragon Claw",
			"Frenzy Plant",
			"Bulk Up",
			"Bounce",
			"Mud Shot",
			"Poison Tail",
			"Covet",
			"Volt Tackle",
			"Magical Leaf",
			"Water Sport",
			"Calm Mind",
			"Leaf Blade",
			"Dragon Dance",
			"Rock Blast",
			"Shock Wave",
			"Water Pulse",
			"Doom Desire",
			"Psycho Boost",
			"Roost",
			"Gravity",
			"Miracle Eye",
			"Wake-Up Slap",
			"Hammer Arm",
			"Gyro Ball",
			"Healing Wish",
			"Brine",
			"Natural Gift",
			"Feint",
			"Pluck",
			"Tailwind",
			"Acupressure",
			"Metal Burst",
			"U-turn",
			"Close Combat",
			"Payback",
			"Assurance",
			"Embargo",
			"Fling",
			"Psycho Shift",
			"Trump Card",
			"Heal Block",
			"Wring Out",
			"Power Trick",
			"Gastro Acid",
			"Lucky Chant",
			"Me First",
			"Copycat",
			"Power Swap",
			"Guard Swap",
			"Punishment",
			"Last Resort",
			"Worry Seed",
			"Sucker Punch",
			"Toxic Spikes",
			"Heart Swap",
			"Aqua Ring",
			"Magnet Rise",
			"Flare Blitz",
			"Force Palm",
			"Aura Sphere",
			"Rock Polish",
			"Poison Jab",
			"Dark Pulse",
			"Night Slash",
			"Aqua Tail",
			"Seed Bomb",
			"Air Slash",
			"X-Scissor",
			"Bug Buzz",
			"Dragon Pulse",
			"Dragon Rush",
			"Power Gem",
			"Drain Punch",
			"Vacuum Wave",
			"Focus Blast",
			"Energy Ball",
			"Brave Bird",
			"Earth Power",
			"Switcheroo",
			"Giga Impact",
			"Nasty Plot",
			"Bullet Punch",
			"Avalanche",
			"Ice Shard",
			"Shadow Claw",
			"Thunder Fang",
			"Ice Fang",
			"Fire Fang",
			"Shadow Sneak",
			"Mud Bomb",
			"Psycho Cut",
			"Zen Headbutt",
			"Mirror Shot",
			"Flash Cannon",
			"Rock Climb",
			"Defog",
			"Trick Room",
			"Draco Meteor",
			"Discharge",
			"Lava Plume",
			"Leaf Storm",
			"Power Whip",
			"Rock Wrecker",
			"Cross Poison",
			"Gunk Shot",
			"Iron Head",
			"Magnet Bomb",
			"Stone Edge",
			"Captivate",
			"Stealth Rock",
			"Grass Knot",
			"Chatter",
			"Judgment",
			"Bug Bite",
			"Charge Beam",
			"Wood Hammer",
			"Aqua Jet",
			"Attack Order",
			"Defend Order",
			"Heal Order",
			"Head Smash",
			"Double Hit",
			"Roar of Time",
			"Spacial Rend",
			"Lunar Dance",
			"Crush Grip",
			"Magma Storm",
			"Dark Void",
			"Seed Flare",
			"Ominous Wind",
			"Shadow Force",
			"Hone Claws",
			"Wide Guard",
			"Guard Split",
			"Power Split",
			"Wonder Room",
			"Psyshock",
			"Venoshock",
			"Autotomize",
			"Rage Powder",
			"Telekinesis",
			"Magic Room",
			"Smack Down",
			"Storm Throw",
			"Flame Burst",
			"Sludge Wave",
			"Quiver Dance",
			"Heavy Slam",
			"Synchronoise",
			"Electro Ball",
			"Soak",
			"Flame Charge",
			"Coil",
			"Low Sweep",
			"Acid Spray",
			"Foul Play",
			"Simple Beam",
			"Entrainment",
			"After You",
			"Round",
			"Echoed Voice",
			"Chip Away",
			"Clear Smog",
			"Stored Power",
			"Quick Guard",
			"Ally Switch",
			"Scald",
			"Shell Smash",
			"Heal Pulse",
			"Hex",
			"Sky Drop",
			"Shift Gear",
			"Circle Throw",
			"Incinerate",
			"Quash",
			"Acrobatics",
			"Reflect Type",
			"Retaliate",
			"Final Gambit",
			"Bestow",
			"Inferno",
			"Water Pledge",
			"Fire Pledge",
			"Grass Pledge",
			"Volt Switch",
			"Struggle Bug",
			"Bulldoze",
			"Frost Breath",
			"Dragon Tail",
			"Work Up",
			"Electroweb",
			"Wild Charge",
			"Drill Run",
			"Dual Chop",
			"Heart Stamp",
			"Horn Leech",
			"Sacred Sword",
			"Razor Shell",
			"Heat Crash",
			"Leaf Tornado",
			"Steamroller",
			"Cotton Guard",
			"Night Daze",
			"Psystrike",
			"Tail Slap",
			"Hurricane",
			"Head Charge",
			"Gear Grind",
			"Searing Shot",
			"Techno Blast",
			"Relic Song",
			"Secret Sword",
			"Glaciate",
			"Bolt Strike",
			"Blue Flare",
			"Fiery Dance",
			"Freeze Shock",
			"Ice Burn",
			"Snarl",
			"Icicle Crash",
			"V-create",
			"Fusion Flare",
			"Fusion Bolt"});
			this.moveboxA.Location = new System.Drawing.Point(52, 19);
			this.moveboxA.Name = "moveboxA";
			this.moveboxA.Size = new System.Drawing.Size(119, 21);
			this.moveboxA.TabIndex = 4;
			// 
			// atkC
			// 
			this.atkC.Location = new System.Drawing.Point(6, 61);
			this.atkC.Name = "atkC";
			this.atkC.Size = new System.Drawing.Size(104, 24);
			this.atkC.TabIndex = 2;
			this.atkC.TabStop = true;
			this.atkC.Text = "C";
			this.atkC.UseVisualStyleBackColor = true;
			this.atkC.CheckedChanged += new System.EventHandler(this.AtkCCheckedChanged);
			// 
			// atkB
			// 
			this.atkB.Location = new System.Drawing.Point(6, 40);
			this.atkB.Name = "atkB";
			this.atkB.Size = new System.Drawing.Size(104, 24);
			this.atkB.TabIndex = 1;
			this.atkB.TabStop = true;
			this.atkB.Text = "B";
			this.atkB.UseVisualStyleBackColor = true;
			this.atkB.CheckedChanged += new System.EventHandler(this.AtkBCheckedChanged);
			// 
			// atkA
			// 
			this.atkA.Location = new System.Drawing.Point(6, 19);
			this.atkA.Name = "atkA";
			this.atkA.Size = new System.Drawing.Size(104, 24);
			this.atkA.TabIndex = 0;
			this.atkA.TabStop = true;
			this.atkA.Text = "A";
			this.atkA.UseVisualStyleBackColor = true;
			this.atkA.CheckedChanged += new System.EventHandler(this.AtkACheckedChanged);
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this.gnd_none);
			this.groupBox1.Controls.Add(this.gnd_male);
			this.groupBox1.Controls.Add(this.gnd_female);
			this.groupBox1.Location = new System.Drawing.Point(5, 223);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(96, 94);
			this.groupBox1.TabIndex = 3;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Gender";
			// 
			// gnd_none
			// 
			this.gnd_none.Location = new System.Drawing.Point(6, 61);
			this.gnd_none.Name = "gnd_none";
			this.gnd_none.Size = new System.Drawing.Size(84, 24);
			this.gnd_none.TabIndex = 6;
			this.gnd_none.TabStop = true;
			this.gnd_none.Text = "Genderless";
			this.gnd_none.UseVisualStyleBackColor = true;
			this.gnd_none.CheckedChanged += new System.EventHandler(this.Gnd_noneCheckedChanged);
			// 
			// gnd_male
			// 
			this.gnd_male.Location = new System.Drawing.Point(6, 19);
			this.gnd_male.Name = "gnd_male";
			this.gnd_male.Size = new System.Drawing.Size(72, 24);
			this.gnd_male.TabIndex = 4;
			this.gnd_male.TabStop = true;
			this.gnd_male.Text = "Male";
			this.gnd_male.UseVisualStyleBackColor = true;
			this.gnd_male.CheckedChanged += new System.EventHandler(this.Gnd_maleCheckedChanged);
			// 
			// gnd_female
			// 
			this.gnd_female.Location = new System.Drawing.Point(6, 40);
			this.gnd_female.Name = "gnd_female";
			this.gnd_female.Size = new System.Drawing.Size(72, 24);
			this.gnd_female.TabIndex = 5;
			this.gnd_female.TabStop = true;
			this.gnd_female.Text = "Female";
			this.gnd_female.UseVisualStyleBackColor = true;
			this.gnd_female.CheckedChanged += new System.EventHandler(this.Gnd_femaleCheckedChanged);
			// 
			// area_label
			// 
			this.area_label.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.area_label.Location = new System.Drawing.Point(5, 9);
			this.area_label.Name = "area_label";
			this.area_label.Size = new System.Drawing.Size(196, 60);
			this.area_label.TabIndex = 4;
			this.area_label.Text = "Dream World Area";
			this.area_label.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// ok_but
			// 
			this.ok_but.Location = new System.Drawing.Point(117, 255);
			this.ok_but.Name = "ok_but";
			this.ok_but.Size = new System.Drawing.Size(75, 23);
			this.ok_but.TabIndex = 5;
			this.ok_but.Text = "OK";
			this.ok_but.UseVisualStyleBackColor = true;
			this.ok_but.Click += new System.EventHandler(this.Ok_butClick);
			// 
			// cancel_but
			// 
			this.cancel_but.Location = new System.Drawing.Point(117, 284);
			this.cancel_but.Name = "cancel_but";
			this.cancel_but.Size = new System.Drawing.Size(75, 23);
			this.cancel_but.TabIndex = 6;
			this.cancel_but.Text = "Cancel";
			this.cancel_but.UseVisualStyleBackColor = true;
			this.cancel_but.Click += new System.EventHandler(this.Cancel_butClick);
			// 
			// exclusive_label
			// 
			this.exclusive_label.ForeColor = System.Drawing.Color.Red;
			this.exclusive_label.Location = new System.Drawing.Point(119, 69);
			this.exclusive_label.Name = "exclusive_label";
			this.exclusive_label.Size = new System.Drawing.Size(65, 23);
			this.exclusive_label.TabIndex = 7;
			this.exclusive_label.Text = "B2W2 Only";
			this.exclusive_label.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// Entralink_DreamWorld
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(206, 322);
			this.Controls.Add(this.exclusive_label);
			this.Controls.Add(this.cancel_but);
			this.Controls.Add(this.ok_but);
			this.Controls.Add(this.area_label);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this.Move);
			this.Controls.Add(this.label1);
			this.Controls.Add(this.speciesbox);
			this.Name = "Entralink_DreamWorld";
			this.Text = "Dream World";
			this.Move.ResumeLayout(false);
			this.groupBox1.ResumeLayout(false);
			this.ResumeLayout(false);

		}
	}
}
